server {
    listen 80;
    server_name localhost;

    root /var/www/kasir-pos;
    index index.kasir.html;

    access_log /var/log/nginx/kasir-pos.access.log;
    error_log /var/log/nginx/kasir-pos.error.log;

    location / {
        try_files $uri $uri/ /index.kasir.html;
    }

    location ~* \.(?:css|js|png|jpg|jpeg|gif|svg|ico|json|webp)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
        access_log off;
        try_files $uri =404;
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }
}
